### ISSUE TITLE
Finish glossary.html

### ISSUE THREAD

**Issue by tajenli** [tajenli/github-for-web-designers#1]
Dadali,
Please finish `glossary.html`. It needs **terms** and **definitions**. 
Thanks,
Darren

**Comment by dadali-bt** [comment]
Yup, I will work on it tonight!

**Comment by tajenli** [comment]
Great! I close the issue.

**Comment by dadali-bt** [comment]
I won't be done tonight. So I re-open the issue!

**Comment by tajenli** [comment]
I see, that's OK, thank you for your help. I will close the issue now.
